/* Tanda TekPair (cola) — posts nuevos, 6 idiomas. Mismo formato que gen-semana.content.js.
   Temas frescos (no duplican lo ya publicado). Contenido orientativo, sin afirmaciones
   legales/fiscales concretas (se remite a la normativa vigente / asesor). */

const CH = {
  es: { nav_feat: 'Funcionalidades', nav_price: 'Precios', nav_login: 'Iniciar sesión', toc_title: 'En este artículo', faq_title: 'Preguntas frecuentes', foot_tag: 'Software de gestión para talleres de reparación', foot_priv: 'Privacidad', foot_terms: 'Términos' },
  en: { nav_feat: 'Features', nav_price: 'Pricing', nav_login: 'Log in', toc_title: 'In this article', faq_title: 'Frequently asked questions', foot_tag: 'Management software for repair shops', foot_priv: 'Privacy', foot_terms: 'Terms' },
  fr: { nav_feat: 'Fonctionnalités', nav_price: 'Tarifs', nav_login: 'Se connecter', toc_title: 'Dans cet article', faq_title: 'Questions fréquentes', foot_tag: 'Logiciel de gestion pour ateliers de réparation', foot_priv: 'Confidentialité', foot_terms: 'Conditions' },
  it: { nav_feat: 'Funzionalità', nav_price: 'Prezzi', nav_login: 'Accedi', toc_title: 'In questo articolo', faq_title: 'Domande frequenti', foot_tag: 'Software gestionale per officine di riparazione', foot_priv: 'Privacy', foot_terms: 'Termini' },
  de: { nav_feat: 'Funktionen', nav_price: 'Preise', nav_login: 'Anmelden', toc_title: 'In diesem Artikel', faq_title: 'Häufige Fragen', foot_tag: 'Verwaltungssoftware für Reparaturwerkstätten', foot_priv: 'Datenschutz', foot_terms: 'AGB' },
  pt: { nav_feat: 'Funcionalidades', nav_price: 'Preços', nav_login: 'Entrar', toc_title: 'Neste artigo', faq_title: 'Perguntas frequentes', foot_tag: 'Software de gestão para oficinas de reparação', foot_priv: 'Privacidade', foot_terms: 'Termos' },
};
const CAT = { es: 'Gestión', en: 'Management', fr: 'Gestion', it: 'Gestione', de: 'Verwaltung', pt: 'Gestão' };
const RT = { es: '6 min de lectura', en: '6 min read', fr: '6 min de lecture', it: '6 min di lettura', de: '6 Min. Lesezeit', pt: '6 min de leitura' };
const RL = { es: 'Leer guía completa →', en: 'Read full guide →', fr: 'Lire le guide complet →', it: 'Leggi la guida completa →', de: 'Anleitung lesen →', pt: 'Ler guia completo →' };
const TRY = { es: 'Pruébalo gratis →', en: 'Try it free →', fr: 'Essayez gratuitement →', it: 'Provalo gratis →', de: 'Kostenlos testen →', pt: 'Experimenta grátis →' };
const ML = {
  es: ['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'],
  en: ['January','February','March','April','May','June','July','August','September','October','November','December'],
  fr: ['janvier','février','mars','avril','mai','juin','juillet','août','septembre','octobre','novembre','décembre'],
  it: ['gennaio','febbraio','marzo','aprile','maggio','giugno','luglio','agosto','settembre','ottobre','novembre','dicembre'],
  de: ['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'],
  pt: ['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'],
};
function longDate(lang, d) {
  const [y, m, dd] = d.split('-').map(Number); const mo = ML[lang][m - 1];
  if (lang === 'es' || lang === 'pt') return dd + ' de ' + mo + ' de ' + y;
  if (lang === 'en') return mo + ' ' + dd + ', ' + y;
  if (lang === 'de') return dd + '. ' + mo + ' ' + y;
  return dd + ' ' + mo + ' ' + y;
}
function mk(lang, date, o) {
  return Object.assign({}, CH[lang], { category: CAT[lang], readtime: RT[lang], readlink: RL[lang], dateLabel: longDate(lang, date) }, o);
}
const LINK = (lang) => '<a href="https://www.tekpair.tech" style="color:var(--terracota-dark);font-weight:600;">' + TRY[lang] + '</a>';

module.exports = [

  // ───────────── 1) ENTRADA / SALIDA DE EQUIPOS ─────────────
  {
    id: 'organizar-entrada-salida-equipos-taller', date: '2026-06-08',
    slug: { es: 'blog/organizar-entrada-salida-equipos-taller.html', en: 'blog/en/track-devices-in-out-repair-shop.html', fr: 'blog/fr/suivi-entree-sortie-appareils-atelier.html', it: 'blog/it/entrata-uscita-dispositivi-officina.html', de: 'blog/de/geraete-ein-ausgang-werkstatt.html', pt: 'blog/pt/entrada-saida-equipamentos-oficina.html' },
    c: {
      es: mk('es', '2026-06-08', { title: 'Cómo organizar la entrada y salida de equipos en tu taller', description: 'Cómo controlar los móviles que entran y salen de tu taller para no perder ninguno ni confundir equipos: resguardo, estado y ubicación.', ogdesc: 'Controla la entrada y salida de equipos sin perder ninguno.', keywords: 'control equipos taller, entrada salida moviles taller, organizar taller reparacion', excerpt: 'Resguardo, estado y ubicación: que no se pierda ni se confunda ningún equipo.', h1: 'Cómo organizar la entrada y salida de equipos en tu taller', heroIntro: 'En un taller con varios móviles a la vez, perder uno o confundir dos es el peor escenario. Con un pequeño sistema de entrada y salida lo evitas y das mejor imagen.', toc: ['Por qué controlar entradas y salidas', 'Qué anotar al recibir un equipo', 'Dónde lo guardas (ubicación)', 'La salida y la entrega'], body: `
    <p>Cuantos más equipos pasan por tu taller, más fácil es que algo se traspapele. Un cliente que vuelve y no encuentras su móvil rápido pierde la confianza al instante. La solución no es memoria, es método.</p>
    <h2 id="s1">1. Por qué controlar entradas y salidas</h2>
    <p>Saber en todo momento qué equipos tienes, de quién son y en qué punto están te ahorra tiempo, discusiones y sustos. Además, te protege: si queda registrado el estado en que entró el móvil, evitas reclamaciones por daños que ya traía.</p>
    <h2 id="s2">2. Qué anotar al recibir un equipo</h2>
    <ul><li>Cliente y teléfono de contacto.</li><li>Marca, modelo e IMEI o número de serie.</li><li>Avería que describe el cliente.</li><li>Estado visible al entrar (golpes, ralladuras, pantalla, etc.).</li><li>Patrón o acceso si el cliente lo facilita para probar (con su permiso).</li></ul>
    <div class="callout"><p><strong>Consejo:</strong> entrega siempre un resguardo con esos datos. Es tu respaldo y le da seguridad al cliente.</p></div>
    <h2 id="s3">3. Dónde lo guardas (ubicación)</h2>
    <p>Asigna una ubicación a cada equipo: estantería, casillero o número de balda. Anótala junto a la reparación. Cuando el cliente vuelva, sabrás en segundos dónde está su móvil sin rebuscar.</p>
    <h2 id="s4">4. La salida y la entrega</h2>
    <p>Antes de entregar, comprueba que la reparación está cerrada, cobrada y probada. Marca el equipo como entregado y guarda la fecha. Así sabes qué sigue en el taller y qué ya salió, sin contar a ojo.</p>
    <div class="callout"><p><strong>TekPair</strong> registra cada equipo con su estado, IMEI y ubicación, y te dice de un vistazo qué está pendiente y qué ya se entregó. ${LINK('es')}</p></div>`, faq: [{ q: '¿Por qué anotar el estado al entrar?', a: 'Para protegerte de reclamaciones por daños previos. Si queda registrado que el móvil ya tenía un golpe o la pantalla rayada, evitas malentendidos al entregar.' }, { q: '¿Hace falta el IMEI de cada equipo?', a: 'Es muy recomendable: identifica el dispositivo de forma única, sirve para la garantía y evita confundir dos móviles del mismo modelo.' }, { q: '¿Cómo evito perder un equipo?', a: 'Asignando una ubicación a cada uno y registrando su estado (pendiente, en reparación, listo, entregado). Así siempre sabes dónde está y en qué punto.' }], cta_h: 'Ningún equipo perdido ni confundido', cta_p: 'TekPair controla la entrada, ubicación y salida de cada móvil de tu taller. Empieza gratis.', cta_btn: 'Empieza gratis en TekPair →' }),
      en: mk('en', '2026-06-08', { title: 'How to track devices in and out of your repair shop', description: 'How to track the phones coming in and out of your shop so none get lost or mixed up: receipt, condition and location.', ogdesc: 'Track devices in and out so none get lost.', keywords: 'track devices repair shop, phones in out workshop, organise repair shop', excerpt: 'Receipt, condition and location so no device gets lost or mixed up.', h1: 'How to track devices in and out of your repair shop', heroIntro: 'In a shop with several phones at once, losing one or mixing two up is the worst case. A small in/out system prevents it and looks more professional.', toc: ['Why track ins and outs', 'What to note when receiving a device', 'Where you store it (location)', 'Checkout and handover'], body: `
    <p>The more devices pass through your shop, the easier something goes astray. A customer whose phone you cannot find fast loses trust instantly. The answer is not memory, it is method.</p>
    <h2 id="s1">1. Why track ins and outs</h2>
    <p>Knowing at all times which devices you hold, whose they are and where they stand saves time, arguments and scares. It also protects you: recording the condition a phone arrived in avoids claims for pre-existing damage.</p>
    <h2 id="s2">2. What to note when receiving a device</h2>
    <ul><li>Customer and contact phone.</li><li>Make, model and IMEI or serial number.</li><li>Fault as described by the customer.</li><li>Visible condition on arrival (dents, scratches, screen, etc.).</li><li>Pattern or access if the customer provides it for testing (with their permission).</li></ul>
    <div class="callout"><p><strong>Tip:</strong> always hand over a receipt with this data. It is your backup and reassures the customer.</p></div>
    <h2 id="s3">3. Where you store it (location)</h2>
    <p>Assign a location to each device: shelf, locker or slot number. Note it with the repair. When the customer returns, you will know in seconds where their phone is.</p>
    <h2 id="s4">4. Checkout and handover</h2>
    <p>Before handing over, check the repair is closed, paid and tested. Mark the device as delivered and save the date. That way you know what is still in the shop and what has left, without eyeballing it.</p>
    <div class="callout"><p><strong>TekPair</strong> records each device with its condition, IMEI and location, and shows at a glance what is pending and what has been delivered. ${LINK('en')}</p></div>`, faq: [{ q: 'Why note the condition on arrival?', a: 'To protect yourself from claims over pre-existing damage. If it is on record that the phone already had a dent or a scratched screen, you avoid misunderstandings at handover.' }, { q: 'Do I need the IMEI of each device?', a: 'Strongly recommended: it identifies the device uniquely, helps with warranty and stops you mixing up two phones of the same model.' }, { q: 'How do I avoid losing a device?', a: 'By assigning each one a location and recording its status (pending, in repair, ready, delivered). You always know where it is and at what stage.' }], cta_h: 'No device lost or mixed up', cta_p: 'TekPair tracks the intake, location and checkout of every phone in your shop. Start free.', cta_btn: 'Start free on TekPair →' }),
      fr: mk('fr', '2026-06-08', { title: 'Suivre l’entrée et la sortie des appareils de votre atelier', description: 'Comment suivre les téléphones qui entrent et sortent de votre atelier pour n’en perdre ni en confondre aucun : reçu, état et emplacement.', ogdesc: 'Suivez les entrées et sorties sans perdre d’appareil.', keywords: 'suivi appareils atelier, entree sortie telephones atelier, organiser atelier reparation', excerpt: 'Reçu, état et emplacement : aucun appareil perdu ni confondu.', h1: 'Suivre l’entrée et la sortie des appareils de votre atelier', heroIntro: 'Dans un atelier avec plusieurs téléphones à la fois, en perdre un ou en confondre deux est le pire scénario. Un petit système d’entrée/sortie l’évite et fait plus pro.', toc: ['Pourquoi suivre entrées et sorties', 'Quoi noter à la réception', 'Où le ranger (emplacement)', 'La sortie et la remise'], body: `
    <p>Plus d’appareils passent par votre atelier, plus il est facile d’en égarer un. Un client dont vous ne retrouvez pas vite le téléphone perd confiance aussitôt. La réponse n’est pas la mémoire, c’est la méthode.</p>
    <h2 id="s1">1. Pourquoi suivre entrées et sorties</h2>
    <p>Savoir à tout moment quels appareils vous détenez, à qui ils sont et où ils en sont fait gagner du temps et évite les litiges. Cela vous protège aussi : noter l’état d’arrivée évite les réclamations pour des dommages préexistants.</p>
    <h2 id="s2">2. Quoi noter à la réception</h2>
    <ul><li>Client et téléphone de contact.</li><li>Marque, modèle et IMEI ou numéro de série.</li><li>Panne décrite par le client.</li><li>État visible à l’arrivée (chocs, rayures, écran, etc.).</li><li>Schéma ou accès si le client le fournit pour tester (avec son accord).</li></ul>
    <div class="callout"><p><strong>Conseil :</strong> remettez toujours un reçu avec ces données. C’est votre preuve et cela rassure le client.</p></div>
    <h2 id="s3">3. Où le ranger (emplacement)</h2>
    <p>Attribuez un emplacement à chaque appareil : étagère, casier ou numéro. Notez-le avec la réparation. Au retour du client, vous saurez en quelques secondes où est son téléphone.</p>
    <h2 id="s4">4. La sortie et la remise</h2>
    <p>Avant de remettre, vérifiez que la réparation est close, payée et testée. Marquez l’appareil comme remis et gardez la date. Vous savez ainsi ce qui reste et ce qui est sorti.</p>
    <div class="callout"><p><strong>TekPair</strong> enregistre chaque appareil avec son état, IMEI et emplacement, et montre d’un coup d’œil ce qui est en attente et ce qui est remis. ${LINK('fr')}</p></div>`, faq: [{ q: 'Pourquoi noter l’état à l’arrivée ?', a: 'Pour vous protéger des réclamations sur des dommages préexistants. Si l’on a noté que le téléphone avait déjà un choc ou un écran rayé, on évite les malentendus à la remise.' }, { q: 'Faut-il l’IMEI de chaque appareil ?', a: 'Fortement recommandé : il identifie l’appareil de façon unique, sert pour la garantie et évite de confondre deux téléphones du même modèle.' }, { q: 'Comment éviter de perdre un appareil ?', a: 'En attribuant un emplacement à chacun et en enregistrant son statut (en attente, en réparation, prêt, remis). Vous savez toujours où il est.' }], cta_h: 'Aucun appareil perdu ni confondu', cta_p: 'TekPair suit la réception, l’emplacement et la sortie de chaque téléphone de votre atelier. Commencez gratuitement.', cta_btn: 'Commencer gratuitement sur TekPair →' }),
      it: mk('it', '2026-06-08', { title: 'Come gestire entrata e uscita dei dispositivi in officina', description: 'Come tenere traccia dei telefoni che entrano ed escono dalla tua officina per non perderne né confonderne nessuno: ricevuta, stato e posizione.', ogdesc: 'Gestisci entrata e uscita senza perdere dispositivi.', keywords: 'gestione dispositivi officina, entrata uscita telefoni officina, organizzare officina riparazione', excerpt: 'Ricevuta, stato e posizione: nessun dispositivo perso o confuso.', h1: 'Come gestire entrata e uscita dei dispositivi in officina', heroIntro: 'In un’officina con più telefoni insieme, perderne uno o confonderne due è lo scenario peggiore. Un piccolo sistema di entrata/uscita lo evita e dà più professionalità.', toc: ['Perché tracciare entrate e uscite', 'Cosa annotare alla ricezione', 'Dove riporlo (posizione)', 'L’uscita e la consegna'], body: `
    <p>Più dispositivi passano dalla tua officina, più è facile che qualcosa si smarrisca. Un cliente a cui non trovi subito il telefono perde fiducia all’istante. La risposta non è la memoria, è il metodo.</p>
    <h2 id="s1">1. Perché tracciare entrate e uscite</h2>
    <p>Sapere sempre quali dispositivi hai, di chi sono e a che punto sono fa risparmiare tempo ed evita discussioni. Ti protegge anche: registrare lo stato all’arrivo evita reclami per danni preesistenti.</p>
    <h2 id="s2">2. Cosa annotare alla ricezione</h2>
    <ul><li>Cliente e telefono di contatto.</li><li>Marca, modello e IMEI o numero di serie.</li><li>Guasto descritto dal cliente.</li><li>Stato visibile all’arrivo (urti, graffi, schermo, ecc.).</li><li>Sequenza o accesso se il cliente lo fornisce per provare (col suo permesso).</li></ul>
    <div class="callout"><p><strong>Consiglio:</strong> consegna sempre una ricevuta con questi dati. È la tua prova e dà sicurezza al cliente.</p></div>
    <h2 id="s3">3. Dove riporlo (posizione)</h2>
    <p>Assegna una posizione a ogni dispositivo: scaffale, armadietto o numero. Annotala con la riparazione. Al ritorno del cliente saprai in pochi secondi dov’è il telefono.</p>
    <h2 id="s4">4. L’uscita e la consegna</h2>
    <p>Prima di consegnare, verifica che la riparazione sia chiusa, pagata e testata. Segna il dispositivo come consegnato e salva la data. Così sai cosa resta e cosa è uscito.</p>
    <div class="callout"><p><strong>TekPair</strong> registra ogni dispositivo con stato, IMEI e posizione, e mostra a colpo d’occhio cosa è in sospeso e cosa è consegnato. ${LINK('it')}</p></div>`, faq: [{ q: 'Perché annotare lo stato all’arrivo?', a: 'Per proteggerti da reclami su danni preesistenti. Se è registrato che il telefono aveva già un urto o lo schermo graffiato, eviti malintesi alla consegna.' }, { q: 'Serve l’IMEI di ogni dispositivo?', a: 'Molto consigliato: identifica il dispositivo in modo univoco, serve per la garanzia ed evita di confondere due telefoni dello stesso modello.' }, { q: 'Come evito di perdere un dispositivo?', a: 'Assegnando una posizione a ciascuno e registrando lo stato (in attesa, in riparazione, pronto, consegnato). Sai sempre dov’è.' }], cta_h: 'Nessun dispositivo perso o confuso', cta_p: 'TekPair traccia ingresso, posizione e uscita di ogni telefono della tua officina. Inizia gratis.', cta_btn: 'Inizia gratis su TekPair →' }),
      de: mk('de', '2026-06-08', { title: 'Geräte-Ein- und -Ausgang in der Werkstatt organisieren', description: 'Wie du die Handys, die in deine Werkstatt kommen und gehen, im Griff behältst, damit keines verloren geht oder verwechselt wird: Beleg, Zustand, Ort.', ogdesc: 'Ein- und Ausgang im Griff, kein Gerät geht verloren.', keywords: 'geraete verwalten werkstatt, ein ausgang handys werkstatt, reparaturwerkstatt organisieren', excerpt: 'Beleg, Zustand und Ort: kein Gerät geht verloren oder wird verwechselt.', h1: 'Geräte-Ein- und -Ausgang in der Werkstatt organisieren', heroIntro: 'In einer Werkstatt mit mehreren Handys zugleich ist eines zu verlieren oder zwei zu verwechseln der Worst Case. Ein kleines Ein-/Ausgangssystem verhindert das und wirkt professioneller.', toc: ['Warum Ein-/Ausgang verfolgen', 'Was bei Annahme notieren', 'Wo lagern (Ort)', 'Ausgang und Übergabe'], body: `
    <p>Je mehr Geräte durch deine Werkstatt gehen, desto leichter geht etwas verloren. Ein Kunde, dessen Handy du nicht schnell findest, verliert sofort das Vertrauen. Die Lösung ist nicht Gedächtnis, sondern Methode.</p>
    <h2 id="s1">1. Warum Ein-/Ausgang verfolgen</h2>
    <p>Jederzeit zu wissen, welche Geräte du hast, wem sie gehören und wo sie stehen, spart Zeit und vermeidet Streit. Es schützt dich auch: den Ankunftszustand zu erfassen, verhindert Ansprüche wegen Vorschäden.</p>
    <h2 id="s2">2. Was bei Annahme notieren</h2>
    <ul><li>Kunde und Kontaktnummer.</li><li>Marke, Modell und IMEI oder Seriennummer.</li><li>Vom Kunden beschriebener Fehler.</li><li>Sichtbarer Zustand bei Annahme (Dellen, Kratzer, Display usw.).</li><li>Muster oder Zugang, falls der Kunde es zum Testen gibt (mit Erlaubnis).</li></ul>
    <div class="callout"><p><strong>Tipp:</strong> gib immer einen Beleg mit diesen Daten. Er ist dein Nachweis und gibt dem Kunden Sicherheit.</p></div>
    <h2 id="s3">3. Wo lagern (Ort)</h2>
    <p>Weise jedem Gerät einen Ort zu: Regal, Fach oder Nummer. Notiere ihn zur Reparatur. Beim Wiederkommen weißt du in Sekunden, wo das Handy ist.</p>
    <h2 id="s4">4. Ausgang und Übergabe</h2>
    <p>Vor der Übergabe prüfe, dass die Reparatur abgeschlossen, bezahlt und getestet ist. Markiere das Gerät als übergeben und speichere das Datum. So weißt du, was noch da ist und was raus ist.</p>
    <div class="callout"><p><strong>TekPair</strong> erfasst jedes Gerät mit Zustand, IMEI und Ort und zeigt auf einen Blick, was offen und was übergeben ist. ${LINK('de')}</p></div>`, faq: [{ q: 'Warum den Zustand bei Annahme notieren?', a: 'Um dich vor Ansprüchen wegen Vorschäden zu schützen. Ist erfasst, dass das Handy schon eine Delle oder einen Kratzer hatte, vermeidest du Missverständnisse bei der Übergabe.' }, { q: 'Brauche ich die IMEI jedes Geräts?', a: 'Sehr zu empfehlen: Sie identifiziert das Gerät eindeutig, hilft bei der Garantie und verhindert das Verwechseln zweier gleicher Modelle.' }, { q: 'Wie vermeide ich, ein Gerät zu verlieren?', a: 'Indem du jedem einen Ort zuweist und den Status erfasst (offen, in Reparatur, fertig, übergeben). Du weißt immer, wo es ist.' }], cta_h: 'Kein Gerät verloren oder verwechselt', cta_p: 'TekPair verfolgt Annahme, Ort und Ausgang jedes Handys deiner Werkstatt. Kostenlos starten.', cta_btn: 'Kostenlos mit TekPair starten →' }),
      pt: mk('pt', '2026-06-08', { title: 'Como organizar a entrada e saída de equipamentos na oficina', description: 'Como controlar os telemóveis que entram e saem da tua oficina para não perder nem confundir nenhum: comprovativo, estado e localização.', ogdesc: 'Controla entradas e saídas sem perder equipamentos.', keywords: 'controlo equipamentos oficina, entrada saida telemoveis oficina, organizar oficina reparacao', excerpt: 'Comprovativo, estado e localização: nenhum equipamento perdido ou confundido.', h1: 'Como organizar a entrada e saída de equipamentos na oficina', heroIntro: 'Numa oficina com vários telemóveis ao mesmo tempo, perder um ou confundir dois é o pior cenário. Um pequeno sistema de entrada/saída evita-o e dá mais profissionalismo.', toc: ['Porquê controlar entradas e saídas', 'O que anotar ao receber', 'Onde o guardas (localização)', 'A saída e a entrega'], body: `
    <p>Quantos mais equipamentos passam pela tua oficina, mais fácil é algo extraviar-se. Um cliente a quem não encontras logo o telemóvel perde a confiança na hora. A resposta não é a memória, é o método.</p>
    <h2 id="s1">1. Porquê controlar entradas e saídas</h2>
    <p>Saber a todo o momento que equipamentos tens, de quem são e em que ponto estão poupa tempo e evita discussões. Também te protege: registar o estado de entrada evita reclamações por danos preexistentes.</p>
    <h2 id="s2">2. O que anotar ao receber</h2>
    <ul><li>Cliente e telefone de contacto.</li><li>Marca, modelo e IMEI ou número de série.</li><li>Avaria descrita pelo cliente.</li><li>Estado visível à entrada (mossas, riscos, ecrã, etc.).</li><li>Padrão ou acesso se o cliente o facultar para testar (com a sua permissão).</li></ul>
    <div class="callout"><p><strong>Dica:</strong> entrega sempre um comprovativo com estes dados. É o teu respaldo e dá segurança ao cliente.</p></div>
    <h2 id="s3">3. Onde o guardas (localização)</h2>
    <p>Atribui uma localização a cada equipamento: prateleira, cacifo ou número. Anota-a junto da reparação. Quando o cliente voltar, sabes em segundos onde está o telemóvel.</p>
    <h2 id="s4">4. A saída e a entrega</h2>
    <p>Antes de entregar, confirma que a reparação está fechada, paga e testada. Marca o equipamento como entregue e guarda a data. Assim sabes o que continua na oficina e o que já saiu.</p>
    <div class="callout"><p><strong>TekPair</strong> regista cada equipamento com estado, IMEI e localização, e mostra num relance o que está pendente e o que foi entregue. ${LINK('pt')}</p></div>`, faq: [{ q: 'Porquê anotar o estado à entrada?', a: 'Para te protegeres de reclamações por danos preexistentes. Se ficar registado que o telemóvel já tinha uma mossa ou o ecrã riscado, evitas mal-entendidos na entrega.' }, { q: 'Preciso do IMEI de cada equipamento?', a: 'Muito recomendável: identifica o dispositivo de forma única, serve para a garantia e evita confundir dois telemóveis do mesmo modelo.' }, { q: 'Como evito perder um equipamento?', a: 'Atribuindo uma localização a cada um e registando o estado (pendente, em reparação, pronto, entregue). Sabes sempre onde está.' }], cta_h: 'Nenhum equipamento perdido ou confundido', cta_p: 'O TekPair controla a entrada, localização e saída de cada telemóvel da tua oficina. Começa grátis.', cta_btn: 'Começa grátis no TekPair →' }),
    },
  },

];
